name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Build, Test and Publish
        working-directory: .
        run: |
          npm ci
          npm shrinkwrap
          npm run test
          cp package.json /build/package.json
          rm .gitignore
          cp .github/workflows/release.gitignore .gitignore
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
